name: Economy
version: ${project.version}
main: com.clarence.economy.Economy
api-version: '1.21'
commands:
  balance:
    description: Take a brief look at how much money you have in your account.
  shop:
    description: Shop for items in the store.
